# Guide inspiration
# https://gitlab.com/dwt1/dotfiles/-/blob/master/.config/alacritty/alacritty.toml
# Key bindings and some colors not import

# Theme
import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[colors]
draw_bold_text_with_bright_colors = true

[colors.cursor]
cursor = "#528bff"
text = "CellBackground"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
# family = "Source Code Pro"
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
# family = "Source Code Pro"
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
# family = "Source Code Pro"
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
# family = "Source Code Pro"
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 1

[scrolling]
history = 5000

[window]
dynamic_padding = false
opacity = 1.0
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 2
y = 2

